# Generated by Django 3.1 on 2020-09-07 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diferencial', models.CharField(max_length=255)),
                ('img_banner', models.ImageField(upload_to='banner_img/%Y/%m/0')),
                ('tipo_link', models.CharField(choices=[('P', 'Por produto'), ('M', 'Por marca'), ('C', 'Por categoria')], default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_generico', models.CharField(max_length=255)),
                ('descricao_curta', models.TextField(max_length=255)),
                ('descricao_longa', models.TextField()),
                ('marca', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao_var', models.TextField(max_length=255)),
                ('preco', models.FloatField()),
                ('desconto_var', models.FloatField(default=0)),
                ('estoque', models.PositiveIntegerField(default=1)),
                ('imagem', models.ImageField(upload_to='produto_img/%Y/%m/0')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
            },
        ),
    ]
